databases:
  - name: getit-db
    plan: free
    databaseName: getit
    user: getit

services:
  - type: web
    name: getit
    runtime: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn getit.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: getit-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.4"
