# Generated by Django 6.1.1 on 2026-09-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
